# Generated by Django 4.2.30 on 2026-04-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(default='Unknown', max_length=200)),
                ('rating', models.FloatField(default=0.0)),
                ('num_reviews', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('book_url', models.URLField(max_length=500, unique=True)),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('price', models.CharField(blank=True, default='', max_length=20)),
                ('availability', models.CharField(blank=True, default='', max_length=100)),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('ai_genre', models.CharField(blank=True, default='', max_length=100)),
                ('ai_sentiment', models.CharField(blank=True, default='', max_length=50)),
                ('ai_recommendation_text', models.TextField(blank=True, default='')),
                ('insights_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
